apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    path: ampleApp/Cert-Manager
    repoURL: >-
      https://github.com/vishnu1077/ArgoCD
    targetRevision: main
  project: lec
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
